### ISSUE TITLE
Prepare tests and integrate it with Travis

### ISSUE THREAD

**Issue by davidmogar** [davidmogar/normalizr#11]
Now that there is a pull request that adds some tests (#10) would be nice to integrate the project with Travis. On hold till the requests gets merged.

**Comment by feinsteinben** [comment]
Hi @davidmogar ,

I may assist with it during the weekend, if needed.

Cheers,
Ben

**Comment by davidmogar** [comment]
No worries. I'll do it ;)

**Comment by davidmogar** [comment]
Done.
