### ISSUE TITLE
New name for the library

### ISSUE THREAD

**Issue by davidmogar** [davidmogar/normalizr#12]
[This library](https://github.com/paularmstrong/normalizr) is so active that makes so difficult to find Normalizr. Would be nice to have a new name. Thinking about it...

**Comment by feinsteinben** [comment]
What about Texty? Textify?

**Comment by davidmogar** [comment]
New proposal: pyzr /ˈpaɪzɚ/

**Comment by davidmogar** [comment]
New proposal: kukko

**Comment by davidmogar** [comment]
New proposal: _**kanonisk**_
