### ISSUE TITLE
"loading" text

### ISSUE THREAD

**Issue by DruidSmith** [davidmogar/normalizr#6]
Can you either completely remove the print('loading') statement in line 42 of normalizr.py or have it suppressed by default with option to turn it on if needed?

I'm applying the function to a pandas dataframe via .apply function and it gets really noisy having 'loading' printing out unnecessarily a whole bunch of times.

**Comment by davidmogar** [comment]
Hi @DruidSmith,

As I mentioned in your pull request, the change was needed but the way to do it was not what I had in mind to fix it. Hope [last change](https://github.com/davidmogar/normalizr/releases/tag/0.1.9) is good enough for you. If not, let me know.
